version: '3'

services:
  # demoapp:
  #   image: suonto/demoapp
  #   # expose:
  #   #   - 7272
  #   ports:
  #     - "7272:7272"
  #   networks:
  #     - selenium-grid

  hub:
    image: selenium/hub
    # expose:
    #   - 4444
    ports:
      - "4444:4444"
    environment: 
      - GRID_BROWSER_TIMEOUT=3400
      - GRID_TIMEOUT=3600      
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5902:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5901:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

  test-gc:
    build: robot
    command: -v BROWSER:gc --outputdir /out  --log ChromeTesting_log.html --report ChromeTesting_report.html --output ChromeTesting.xml  /tests
    volumes:
      - ./robot/tests:/tests:ro
      - ./results/gc:/out:rw
    depends_on:
      # - demoapp
      - chrome
    networks:
      - selenium-grid

  test-ff:
    build: robot
    command: -v BROWSER:ff --outputdir /out  --log FirefoxTesting_log.html --report FirefoxTesting_report.html --output FirefoxTesting.xml  /tests
    volumes:
      - ./robot/tests:/tests:ro
      - ./results/ff:/out:rw
    depends_on:
      # - demoapp
      - firefox
    networks:
      - selenium-grid

networks:
  selenium-grid: